//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCoordTrans_v2._1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=\"|DataDirectory|\\cdb.mdb\";Persist Se" +
            "curity Info=True")]
        public string Constring {
            get {
                return ((string)(this["Constring"]));
            }
            set {
                this["Constring"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SOFTWARE\\\\Umbrella Technology\\\\GeoCoordTrans")]
        public string register {
            get {
                return ((string)(this["register"]));
            }
            set {
                this["register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Input - Make CSV file</string>
  <string>Input - Select file</string>
  <string>Input - Select separator</string>
  <string>Input - Coordinate type</string>
  <string>Input - Activate fieldnames</string>
  <string>Input - Select fieldnames</string>
  <string>Input - Coordinate system</string>
  <string>Input - Unit</string>
  <string>Output - Select file</string>
  <string>Output - Coordinate type</string>
  <string>Output - Coordinate system</string>
  <string>Output - Unit</string>
  <string>Convert</string>
  <string>Finish</string>
</ArrayOfString>")]
        public string[] pageInfo {
            get {
                return ((string[])(this["pageInfo"]));
            }
            set {
                this["pageInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Easting</string>
  <string>EASTING</string>
  <string>EAST</string>
  <string>X</string>
  <string>x</string>
  <string>Longitude</string>
  <string>longitude</string>
  <string>easting</string>
  <string>E</string>
  <string>East</string>
  <string>east</string>
  <string>e</string>
  <string>long</string>
  <string>Lng</string>
  <string>LNG</string>
  <string>lng</string>
  <string>Long</string>
  <string>LONG</string>
  <string>LON</string>
  <string>Lon</string>
  <string>lon</string>
</ArrayOfString>")]
        public string[] XNames {
            get {
                return ((string[])(this["XNames"]));
            }
            set {
                this["XNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Northing</string>
  <string>NORTH</string>
  <string>LATITUDE</string>
  <string>Y</string>
  <string>y</string>
  <string>Latitude</string>
  <string>latitude</string>
  <string>northing</string>
  <string>N</string>
  <string>North</string>
  <string>north</string>
  <string>n</string>
  <string>lat</string>
  <string>Lat</string>
  <string>lat</string>
  <string>LAT</string>
</ArrayOfString>")]
        public string[] YNames {
            get {
                return ((string[])(this["YNames"]));
            }
            set {
                this["YNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Height</string>
  <string>HEIGHT</string>
  <string>height</string>
  <string>Z</string>
  <string>z</string>
  <string>Elevation</string>
  <string>Elev</string>
  <string>elev</string>
  <string>ELEV</string>
  <string>ELEVATION</string>
  <string>elevation</string>
  <string>ALT</string>
  <string>alt</string>
  <string>ALTITUDE</string>
  <string>Altitude</string>
  <string>altitude</string>
</ArrayOfString>")]
        public string[] ZNames {
            get {
                return ((string[])(this["ZNames"]));
            }
            set {
                this["ZNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ID</string>
  <string>id</string>
  <string>iD</string>
  <string>Id</string>
  <string>pointid</string>
  <string>Point ID</string>
  <string>Pt_ID</string>
  <string>PT_ID</string>
  <string>_ID</string>
  <string>ptID</string>
</ArrayOfString>")]
        public string[] IDNames {
            get {
                return ((string[])(this["IDNames"]));
            }
            set {
                this["IDNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Input database - select database</string>
  <string>Select output table</string>
  <string>Input table - select table</string>
  <string>Input table - type</string>
  <string>Input table - select columns</string>
  <string>Input table - select system</string>
  <string>Input table - select unit</string>
  <string>Output table - enter name</string>
  <string>Output table - type</string>
  <string>Output table - system</string>
  <string>Output table - Select unit</string>
  <string>Convert</string>
  <string>Finish</string>
</ArrayOfString>")]
        public string[] PageInfo2 {
            get {
                return ((string[])(this["PageInfo2"]));
            }
            set {
                this["PageInfo2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SOFTWARE\\\\Umbrella Technology\\\\Protection")]
        public string Protection {
            get {
                return ((string)(this["Protection"]));
            }
            set {
                this["Protection"] = value;
            }
        }
    }
}
